server:
  port: 8081

spring:
  application:
    name: synclifeRoom


  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:ddl.sql


