server:
  port: 8081

spring:
  application:
    name: synclifeRoom


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

#jwt:
#  secretKey: ${SECRETKEY}
#
#  access:
#    expiration: 1800000 # 30분 (1000L(ms -> s) * 60L(s -> m) * 30L)
#    header: "Authorization"
#
#  refresh:
#    expiration: 1209600000 # 2주 (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
#    header: "Authorization-refresh"


#logging:
#  level:
#    org.hibernate.SQL: trace
#    org.hibernate.type.descriptor: trace
#    root: info
#    org.springframework.data.redis: trace


